### ISSUE TITLE
clone gists instead of downloading text files

### ISSUE THREAD

**Issue by enjalot** [enjalot/blockbuilder-search-index#10]
I have an experimental file where I clone entire gists from our list of blocks. This ends up taking up about 2x the space of just the text files (current way we are indexing). Thats still only about 4gb which is rather trivial.

I'd like to do this at the same time we refactor to store the downloaded gist content by user ( #3 )

**Comment by micahstubbs** [comment]
@enjalot is this issue out of date?  I feel like this might have already been done.

**Comment by enjalot** [comment]
yep, I did this a while ago. thanks!
