### ISSUE TITLE
document solution to JavaScript heap out of memory when indexing blocks to elasticsearch

### ISSUE THREAD

**Issue by micahstubbs** [enjalot/blockbuilder-search-index#23]
ninja edit:  the solution is to increase the max memory available to nodejs with this command:

`coffee --nodejs --max-old-space-size=8000 elasticsearch.coffee`

---

when running the command `coffee elasticsearch.coffee`

![screen shot 2017-07-03 at 11 26 45 pm](https://user-images.githubusercontent.com/2119400/27817648-1fe4c4e2-6047-11e7-9579-06e88a7c1343.png)

**Comment by enjalot** [comment]
A workaround is to set the maximum space node is allowed to use like so:
`coffee --max-old-space-size=8000 elasticsearch.coffee`

**Comment by micahstubbs** [comment]
thanks for the tip!  trying 

`coffee --max-old-space-size=8000 elasticsearch.coffee`

I see this error message:

![screen shot 2017-07-04 at 5 21 19 pm](https://user-images.githubusercontent.com/2119400/27844908-45f95490-60dd-11e7-8c24-6b6ed5af1aee.png)

will experiment some more and see if I can get it working 🤔

**Comment by enjalot** [comment]
ah, i think you need:
`coffee --nodejs --max-old-space-size=8000 elasticsearch.coffee`

**Comment by micahstubbs** [comment]
🙏  that `--nodejs` was what I needed

![screen shot 2017-07-04 at 9 18 25 pm](https://user-images.githubusercontent.com/2119400/27848981-5a9c5e3a-60fe-11e7-8562-ae6f2d58d2bb.png)
